### ISSUE TITLE
CssSyntaxError: Missed semicolon

### ISSUE THREAD

**Issue by Bubacarr** [cretueusebiu/laravel-vue-spa#216] opened 2019-10-15 14:04 UTC
hi Just a question about production.

when i run npm run production i get this error

`CssSyntaxError: /dist/css/app.3f044f.css:12360:13: Missed semicolon
    at Input.error (/Users/CHE/code/facars/node_modules/postcss/lib/input.js:130:16)
    at Parser.checkMissedSemicolon (/Users/CHE/code/facars/node_modules/postcss/lib/parser.js:603:22)
    at Parser.decl (/Users/CHE/code/facars/node_modules/postcss/lib/parser.js:286:46)
    at Parser.other (/Users/CHE/code/facars/node_modules/postcss/lib/parser.js:166:12)
    at Parser.parse (/Users/CHE/code/facars/node_modules/postcss/lib/parser.js:77:16)
    at parse (/Users/CHE/code/facars/node_modules/postcss/lib/parse.js:17:12)
    at new LazyResult (/Users/CHE/code/facars/node_modules/postcss/lib/lazy-result.js:60:16)
    at Processor.<anonymous> (/Users/CHE/code/facars/node_modules/postcss/lib/processor.js:138:12)
    at Processor.process (/Users/CHE/code/facars/node_modules/postcss/lib/processor.js:117:23)
    at Function.creator.process (/Users/CHE/code/facars/node_modules/postcss/lib/postcss.js:148:43)
    at OptimizeCssAssetsWebpackPlugin.processCss (/Users/CHE/code/facars/node_modules/optimize-css-assets-webpack-plugin/src/index.js:73:21)
    at Object.processor (/Users/CHE/code/facars/node_modules/optimize-css-assets-webpack-plugin/src/index.js:13:18)
    at each (/Users/CHE/code/facars/node_modules/last-call-webpack-plugin/src/index.js:150:10)
    at arrayEach (/Users/CHE/code/facars/node_modules/lodash/_arrayEach.js:15:9)
    at forEach (/Users/CHE/code/facars/node_modules/lodash/forEach.js:38:10)
    at OptimizeCssAssetsWebpackPlugin.process (/Users/CHE/code/facars/node_modules/last-call-webpack-plugin/src/index.js:147:5)
    at compilation.hooks.optimizeChunkAssets.tapPromise.chunks (/Users/CHE/code/facars/node_modules/last-call-webpack-plugin/src/index.js:178:28)
    at _next0 (eval at create (/Users/CHE/code/facars/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:17)
    at _err0 (eval at create (/Users/CHE/code/facars/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:25:1)
    at taskRunner.run (/Users/CHE/code/facars/node_modules/terser-webpack-plugin/dist/index.js:321:9)
    at step (/Users/CHE/code/facars/node_modules/terser-webpack-plugin/dist/TaskRunner.js:87:9)
    at _cacache.default.get.then (/Users/CHE/code/facars/node_modules/terser-webpack-plugin/dist/TaskRunner.js:111:15)
    at tryCatcher (/Users/CHE/code/facars/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/CHE/code/facars/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/Users/CHE/code/facars/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/Users/CHE/code/facars/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/Users/CHE/code/facars/node_modules/bluebird/js/release/promise.js:729:18)
    at Promise._fulfill (/Users/CHE/code/facars/node_modules/bluebird/js/release/promise.js:673:18)
    at Promise._resolveCallback (/Users/CHE/code/facars/node_modules/bluebird/js/release/promise.js:466:57)
    at Promise._settlePromiseFromHandler (/Users/CHE/code/facars/node_modules/bluebird/js/release/promise.js:559:17)
    at Promise._settlePromise (/Users/CHE/code/facars/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/Users/CHE/code/facars/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/Users/CHE/code/facars/node_modules/bluebird/js/release/promise.js:729:18)
    at Promise._fulfill (/Users/CHE/code/facars/node_modules/bluebird/js/release/promise.js:673:18)
    at Promise._resolveCallback (/Users/CHE/code/facars/node_modules/bluebird/js/release/promise.js:466:57)
    at Promise._settlePromiseFromHandler (/Users/CHE/code/facars/node_modules/bluebird/js/release/promise.js:559:17)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ production: `cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --no-progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ production script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.`

**Comment by bmpf** [comment] 2019-10-26 10:33
probably your css its not correct.

**Comment by jassehomar** [comment] 2019-12-02 16:07
I am using Tailwind I encountered the same issue. @Bubacarr did you have a fixed for your issue??

**Comment by Bubacarr** [comment] 2019-12-02 16:37
hey @jassehomar are you also importing moment try to find in all of your components if you are please try to remove it and run npm run prod this is what fix my issue let me know if this also works for you

**Comment by jassehomar** [comment] 2019-12-03 13:53
@Bubacarr , thanks so much :+1: .  I already discovered that yesterday after doing some googling. And now the problem is fixed. I think you can close the issue.

**Closed** 2019-12-03 19:32 UTC

**Comment by Aliseivani** [comment] 2020-05-25 19:41
I had the same problem and in my case it was caused by chart.js component in my project.
